[sitemap]
output_dir = "./test-sitemaps"
max_urls_per_file = 50000
compress = true
base_url = "https://katalog.review.arthistoricum.net"

[processing]
parallel_workers = 2
log_level = "INFO"
test_mode = true

[[cores]]
name = "test_catalog"
url = "http://sdvdmgtestsolr01.slub-dresden.de:8984/solr/ahn-release"
id_field = "id"
date_field = "last_indexed"
url_pattern = "https://katalog.review.arthistoricum.net/id/{id}"
changefreq = "weekly"
batch_size = 5
timeout = 30